global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pfsense'
    static_configs:
      - targets: ['172.16.1.1:9100']

  - job_name: 'loki'
    static_configs:
      - targets: ['172.16.1.57:3100']