prometheus_version: "2.45.0"
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_install_dir: /opt
prometheus_data_dir: /var/lib/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_port: 9090